export const GLOSSARY: Record<string, string> = {
  TMA: 'Tissue microarray: one glass slide holding many small round tissue samples (cores) from different donors, arranged in a grid.',
  core: 'One round tissue sample on a TMA, about 3 mm across. Each position in the grid is named by column letter and row number, e.g. B-2.',
  'core position': 'The grid position of a core on a TMA, e.g. B-2 = column B, row 2.',
  field: 'A square window (about 560 µm) inside a core that is measured at full resolution. Several fields per core are analysed.',
  'donor-region': 'All cores from one donor and one brain region, pooled. Most results are reported per donor-region.',
  replicate: 'A second core from the same donor and brain region, used to check that measurements repeat.',
  stain: 'The antibody used on a slide: NeuN (neurons), 6E10 (amyloid-β plaques) or AT8 (phosphorylated tau).',
  NeuN: 'Antibody that labels neuronal nuclei and cell bodies; used to count neurons.',
  '6E10': 'Antibody against amyloid-β; used to find and classify plaques.',
  AT8: 'Antibody against phosphorylated tau; used to find tangles, pretangles and neuropil threads.',
  DAB: 'The brown chromogen that shows where the antibody bound. Brown = stained.',
  hematoxylin: 'The blue counterstain that colours every cell nucleus.',
  OD: 'Optical density: how much light the stain absorbs. 0 = no stain; higher = darker.',
  'stain threshold': 'The DAB level above which a pixel counts as stained. One threshold is set per slide, blind to diagnosis, so darker or lighter slides stay comparable.',
  calibration: 'Setting the stain threshold for each slide from its own tissue.',
  'compact plaque': 'A plaque with a dense, well-defined core of amyloid.',
  'diffuse plaque': 'A loose, fluffy amyloid deposit without a dense core.',
  'tau+ neuron': 'A neuron whose cell body contains phosphorylated tau: a tangle (dense, flame-shaped) or a pretangle (diffuse staining around the nucleus).',
  'neuropil thread': 'Thin tau-stained fibres between cells; measured as length per mm² of tissue.',
  burden: 'The share of tissue area covered by stain or by objects (e.g. plaque area fraction).',
  density: 'Objects per mm² of usable tissue (folds, holes and artifacts are not counted as tissue).',
  Cellpose: 'A published deep-learning model (Cellpose-SAM) that outlines cells and nuclei.',
  SAM: 'Segment Anything: a published deep-learning model used here to draw precise object outlines.',
  Phikon: 'A published pathology foundation model; its image features help the 6E10 model tell plaques from other deposits.',
  model: 'A trained classifier that looks at each candidate object and gives the probability that it is a real neuron / plaque / tau+ neuron.',
  'random forest': 'The kind of model stainID trains: many decision trees voting on each object, using its size, shape, stain and surroundings.',
  probability: 'The model’s confidence (0–1) that an object is real. Objects above the threshold (usually 0.5) are counted.',
  precision: 'Of the objects the model counts, the share that are correct. High precision = few false detections.',
  recall: 'Of the real objects, the share the model finds. High recall = few missed objects.',
  AUC: 'Area under the ROC curve: how well the model ranks real objects above false ones (0.5 = guessing, 1 = perfect).',
  'leave-one-TMA-out': 'Testing a model on one TMA after training it on all the others, repeated for every TMA — an honest estimate of accuracy on new slides.',
  'training set': 'Candidate objects picked for you to label; the labels teach a new model.',
  'check set': 'Detected objects picked for you to label blind, to check how accurate the current results are.',
  blinded: 'Diagnosis, donor and the model’s answer are hidden while you label, so they cannot influence you.',
  job: 'A step running in the background. You can keep using the app; progress and logs appear on the Workflow page.',
  shard: 'A part of a long run. Splitting into parts lets several processes (or computers) share the work.',
}
